version: 2
jobs:
  build:
    working_directory: ~/enigma-mixin
    docker:      
      - image: circleci/node:12.18.2
      - image: qlikcore/engine:12.700.0
        command: -S AcceptEULA=yes -S DocumentDirectory=./tests/qvf
    steps:
      - checkout:
          path: ~/enigma-mixin
      - run:
          name: Install dependencies
          command: npm install --quiet    
      - setup_remote_docker
      - run:
          name: Spin up environment
          working_directory: ~/enigma-mixin/tests
          command: QIX_ENGINE_VER=12.171.0 QIX_ACCEPT_EULA=yes docker-compose up --build -d
      - run:
          name: Run Test
          command: npm run test
